version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: denote
    container_name: denote
    ports:
      - '8000:8000'
    volumes:
      - './certs/:/certs/:ro'
      - './db/:/var/db/:rw'
    env_file:
      - ./config/denote.env
